[package]
name = "native_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.3"
borsh-derive = "1.5.3"
solana-program = "2.1.5"

[dev-dependencies]
solana-program-test = "2.1.5"
solana-sdk = "2.1.5"